# Welcome to My GitHub Page

| Name       | Introduction                                      | Hobbies                          |
|------------|--------------------------------------------------|----------------------------------|
| John Smith | Hello, I am a junior in the BS IT program. I enjoy coding Python and R. | Programming, making websites |
