table: Name
| Left Aligned | Center Aligned | Right Aligned |
| :----------- |:--------------:| ------------: |
| Data 1       | Data 2         | Data 3        |
| More Data    | Centered Text  | Right Text    |
